stages:
  - dictionary-validator-publish
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

publish-dictionary-validator-docker:
  stage: dictionary-validator-publish
  image: docker:stable
  only:
    changes:
      - Dockerfile
  when: manual
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build --target validator -f Dockerfile -t registry.gitlab.com/tokenmill/clj-luwak/dictionary-validator:2 .
    - docker push registry.gitlab.com/tokenmill/clj-luwak/dictionary-validator:2
    - docker rmi registry.gitlab.com/tokenmill/clj-luwak/dictionary-validator:2

lint-and-unit-test:
  stage: test
  when: always
  image: clojure:tools-deps-alpine
  script:
    - clojure -A:kibit
    - clojure -A:eastwood
    - clojure -A:test

graal-validate-dictionaries:
  stage: test
  when: always
  image: registry.gitlab.com/tokenmill/clj-luwak/dictionary-validator:2
  script:
    - >
      dictionary-validator
      test/resources/dict.csv csv
      test/resources/dict.json json
      test/resources/dict.edn edn
