stages:
  - dictionary-validator-publish
  - test

lint:
  stage: test
  image: borkdude/clj-kondo
  when: always
  script: clj-kondo --lint src test

unit-test:
  stage: test
  when: always
  image: clojure:tools-deps-alpine
  script:
    - clojure -A:test

validate-sample-dictionaries:
  stage: test
  when: always
  image: clojure:tools-deps-alpine
  script:
    - >
      clojure -m beagle.validator
      test/resources/dict.csv csv
      test/resources/dict.json json
      test/resources/dict.edn edn
